apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
  namespace: medilink
  labels:
    app: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: medilink-telemedicine-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: NODE_ENV
              value: "production"
            - name: JWT_SECRET
              value: "secret123"
            - name: MONGO_URI
              value: "mongodb+srv://chiransamiru2002_db_user:Medilink2026@cluster0.ytfzhlz.mongodb.net/telemedicine-service?retryWrites=true&w=majority&appName=Cluster0"
