@echo off
echo Starting MediLink services...
docker-compose up -d
echo Waiting for services to be ready...
timeout /t 10
echo Opening client in browser...
start http://localhost:5173
echo Done! Services are running at http://localhost:5173
