apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: medilink
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: medilink-auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: "production"
            - name: JWT_SECRET
              value: "secret123"
            - name: MONGO_URI
              value: "mongodb+srv://authServicesanka123:sanShani%402001@cluster0.r5lpmjy.mongodb.net/?appName=Cluster0"
