apiVersion: v1
kind: Service
metadata:
  name: ai-symptom-service
  namespace: default
  labels:
    app: ai-symptom-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: ai-symptom-service
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
