apiVersion: v1
kind: Service
metadata:
  name: ai-symptom-service
  namespace: medilink
  labels:
    app: ai-symptom-service
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: ai-symptom-service
