apiVersion: v1
kind: ServiceAccount
metadata:
  name: telemedicine-service
  namespace: default
  labels:
    app: telemedicine-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: telemedicine-service
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: telemedicine-service
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: telemedicine-service
subjects:
  - kind: ServiceAccount
    name: telemedicine-service
    namespace: default
