apiVersion: v1
kind: Secret
metadata:
  name: patient-service-secrets
  namespace: default
  labels:
    app: patient-service
type: Opaque
stringData:
  # Replace with your actual value
  mongo-uri: "mongodb+srv://username:password@cluster.mongodb.net/medilink-patients?retryWrites=true&w=majority"
