apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: default
  labels:
    app: payment-service
data:
  log-level: "info"
  auth-service-url: "http://auth-service:80"
  appointment-service-url: "http://appointment-service:80"
  doctor-service-url: "http://doctor-service:80"
  patient-service-url: "http://patient-service:80"
